name: Dianoga Docker CI, .NET 4.8, Debug
on:
  push:
    branches: [ feature/docker-build-fix ]
env:
  BUILD_CONFIGURATION: Debug
  DIANOGA_DOTNET_VERSION: net48
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker build
        run: |
          cd c:\
          dir
          cd c:\\"Program Files"
          dir
          cd c:\\"Program Files"\Docker\
          dir
          cd c:\\"Program Files"\Docker\Docker
          dir
          DockerCli.exe -SwitchWindowsEngine
          docker build -t antonytm/dianoga-assets:test1 . --platform windows/amd64
      - name: Run custom action
        uses: ./.github/actions/publish-docker-hub
        with:
          build_configuration: ${{ env.BUILD_CONFIGURATION }}
          dotnet_version: ${{ env.DIANOGA_DOTNET_VERSION }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}